spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.217.238.122:5432/test
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: info

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


application:
  title: 샘플
  version: 0.8
