spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://112.217.238.122:5432/test
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zaxxer:
        hikari: OFF
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF            # JDBC 트러블슈팅 경우를 제외하고는 사용 권장 X
      resultset: OFF        # ResultSet 을 포함한 모든 JDBC 호출 정보를 출력
      resultsettable: INFO  # SQL 결과 데이터 Table 형식으로 출력
      sqlonly: OFF          # SQL 만 로그만 출력
      sqltiming: OFF        # SQL + 소요시간 출력
      connection : OFF      # 커넥션 연결/종료 정보 출력

application:
  title: start-module
  version: 0.8
